name: fdd-env
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.7.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - decorator=4.4.1
  - intel-openmp=2019.4
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=8.2.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1
  - pip=19.1
  - python=3.7.3
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11

